"""
Excel program spec writer.
Generates a formatted Excel workbook from a ProgramSpec.
Matches the typical RWE program spec format: one tab per section.
"""

from __future__ import annotations
from pathlib import Path
from .spec_schema import ProgramSpec


def save_excel(spec: ProgramSpec, output_path: str) -> str:
    """Write ProgramSpec to a formatted Excel workbook. Returns the output path."""
    try:
        from openpyxl import Workbook
        from openpyxl.styles import Font, PatternFill, Alignment, Border, Side
    except ImportError:
        raise ImportError("openpyxl not installed. Run: pip install openpyxl")

    wb = Workbook()

    # ── Styles ────────────────────────────────────────────────────────
    header_font = Font(bold=True, size=11, color="FFFFFF")
    header_fill = PatternFill(start_color="1E40AF", end_color="1E40AF", fill_type="solid")
    section_font = Font(bold=True, size=12, color="1E40AF")
    wrap_align = Alignment(wrap_text=True, vertical="top")
    thin_border = Border(
        left=Side(style="thin", color="D1D5DB"),
        right=Side(style="thin", color="D1D5DB"),
        top=Side(style="thin", color="D1D5DB"),
        bottom=Side(style="thin", color="D1D5DB"),
    )

    # Confidence color fills
    high_fill = PatternFill(start_color="DCFCE7", end_color="DCFCE7", fill_type="solid")
    med_fill = PatternFill(start_color="FEF3C7", end_color="FEF3C7", fill_type="solid")
    low_fill = PatternFill(start_color="FEE2E2", end_color="FEE2E2", fill_type="solid")
    inferred_fill = PatternFill(start_color="FEF9C3", end_color="FEF9C3", fill_type="solid")

    def conf_fill(confidence: float):
        if confidence >= 0.8:
            return high_fill
        elif confidence >= 0.6:
            return med_fill
        return low_fill

    def write_header(ws, row, headers):
        for col, h in enumerate(headers, 1):
            cell = ws.cell(row=row, column=col, value=h)
            cell.font = header_font
            cell.fill = header_fill
            cell.alignment = wrap_align
            cell.border = thin_border

    def write_row(ws, row, values, confidence=0.0, explicit="explicit"):
        fill = conf_fill(confidence)
        if explicit in ("inferred", "assumed"):
            fill = inferred_fill
        for col, v in enumerate(values, 1):
            cell = ws.cell(row=row, column=col, value=v)
            cell.alignment = wrap_align
            cell.border = thin_border
            cell.fill = fill

    # ═══════════════════════════════════════════════════════════════════
    # Tab 1: Overview
    # ═══════════════════════════════════════════════════════════════════
    ws = wb.active
    ws.title = "Overview"
    ws.column_dimensions["A"].width = 25
    ws.column_dimensions["B"].width = 60

    ws.cell(row=1, column=1, value="PROGRAM SPEC — DRAFT").font = Font(bold=True, size=14, color="1E40AF")
    ws.cell(row=2, column=1, value="Auto-generated by Protocol Spec Assist").font = Font(italic=True, color="6B7280")

    overview = [
        ("Protocol ID", spec.protocol_id),
        ("Protocol Title", spec.protocol_title or ""),
        ("Generated", spec.generated_at),
        ("Generator Version", spec.generator_version),
        ("", ""),
        ("Study Design", spec.design_type or "Not extracted"),
        ("Study Period", f"{spec.study_period_start or '?'} to {spec.study_period_end or '?'}"),
        ("Data Source", spec.data_source or "Not extracted"),
        ("Data Version", spec.data_source_version or ""),
        ("", ""),
        ("Index Date", spec.index_date_definition or "Not extracted"),
        ("Index Date Term", spec.index_date_sponsor_term or ""),
        ("Index Date Confidence", f"{spec.index_date_confidence:.0%}"),
        ("", ""),
        ("Follow-up End", spec.follow_up_end_definition or "Not extracted"),
        ("Follow-up End Confidence", f"{spec.follow_up_end_confidence:.0%}"),
        ("", ""),
        ("Concepts Extracted", ", ".join(spec.concepts_extracted)),
        ("Low Signal", ", ".join(spec.concepts_with_low_signal) or "None"),
        ("Contradictions", ", ".join(spec.concepts_with_contradictions) or "None"),
    ]

    for i, (label, value) in enumerate(overview, 4):
        ws.cell(row=i, column=1, value=label).font = Font(bold=True) if label else Font()
        ws.cell(row=i, column=2, value=value).alignment = wrap_align

    # ═══════════════════════════════════════════════════════════════════
    # Tab 2: Inclusion Criteria
    # ═══════════════════════════════════════════════════════════════════
    ws_inc = wb.create_sheet("Inclusion Criteria")
    headers = ["ID", "Domain", "Criterion", "Protocol Text", "Operational Definition",
               "Lookback Window", "Page", "Section", "Confidence", "Explicit"]
    ws_inc.column_dimensions["A"].width = 8
    ws_inc.column_dimensions["B"].width = 14
    ws_inc.column_dimensions["C"].width = 25
    ws_inc.column_dimensions["D"].width = 50
    ws_inc.column_dimensions["E"].width = 35
    ws_inc.column_dimensions["F"].width = 18
    ws_inc.column_dimensions["G"].width = 8
    ws_inc.column_dimensions["H"].width = 25
    ws_inc.column_dimensions["I"].width = 12
    ws_inc.column_dimensions["J"].width = 10

    write_header(ws_inc, 1, headers)
    for i, c in enumerate(spec.inclusion_criteria, 2):
        write_row(ws_inc, i, [
            c.criterion_id, c.domain, c.criterion_label, c.description,
            c.operational_definition or "", c.lookback_window or "",
            c.page, c.section or "", f"{c.confidence:.0%}", c.explicit,
        ], confidence=c.confidence, explicit=c.explicit)

    # ═══════════════════════════════════════════════════════════════════
    # Tab 3: Exclusion Criteria
    # ═══════════════════════════════════════════════════════════════════
    ws_exc = wb.create_sheet("Exclusion Criteria")
    write_header(ws_exc, 1, headers)
    ws_exc.column_dimensions["A"].width = 8
    ws_exc.column_dimensions["B"].width = 14
    ws_exc.column_dimensions["C"].width = 25
    ws_exc.column_dimensions["D"].width = 50
    ws_exc.column_dimensions["E"].width = 35
    ws_exc.column_dimensions["F"].width = 18
    ws_exc.column_dimensions["G"].width = 8
    ws_exc.column_dimensions["H"].width = 25
    ws_exc.column_dimensions["I"].width = 12
    ws_exc.column_dimensions["J"].width = 10

    for i, c in enumerate(spec.exclusion_criteria, 2):
        write_row(ws_exc, i, [
            c.criterion_id, c.domain, c.criterion_label, c.description,
            c.operational_definition or "", c.lookback_window or "",
            c.page, c.section or "", f"{c.confidence:.0%}", c.explicit,
        ], confidence=c.confidence, explicit=c.explicit)

    # ═══════════════════════════════════════════════════════════════════
    # Tab 4: Endpoints
    # ═══════════════════════════════════════════════════════════════════
    ws_ep = wb.create_sheet("Endpoints")
    ep_headers = ["ID", "Type", "Label", "Description", "Composite",
                  "Components", "Time-to-Event", "Page", "Section", "Confidence"]
    ws_ep.column_dimensions["A"].width = 8
    ws_ep.column_dimensions["B"].width = 10
    ws_ep.column_dimensions["C"].width = 25
    ws_ep.column_dimensions["D"].width = 50
    ws_ep.column_dimensions["E"].width = 10
    ws_ep.column_dimensions["F"].width = 35
    ws_ep.column_dimensions["G"].width = 14
    ws_ep.column_dimensions["H"].width = 8
    ws_ep.column_dimensions["I"].width = 25
    ws_ep.column_dimensions["J"].width = 12

    write_header(ws_ep, 1, ep_headers)
    for i, ep in enumerate(spec.endpoints, 2):
        write_row(ws_ep, i, [
            ep.endpoint_id, ep.type, ep.label, ep.description,
            "Yes" if ep.is_composite else "No",
            ", ".join(ep.components) if ep.components else "",
            "Yes" if ep.time_to_event else "No",
            ep.page, ep.section or "", f"{ep.confidence:.0%}",
        ], confidence=ep.confidence)

    # ═══════════════════════════════════════════════════════════════════
    # Tab 5: Censoring Rules
    # ═══════════════════════════════════════════════════════════════════
    ws_cr = wb.create_sheet("Censoring Rules")
    cr_headers = ["ID", "Rule Type", "Label", "Description", "Applies To",
                  "Page", "Section", "Confidence"]
    ws_cr.column_dimensions["A"].width = 8
    ws_cr.column_dimensions["B"].width = 16
    ws_cr.column_dimensions["C"].width = 25
    ws_cr.column_dimensions["D"].width = 50
    ws_cr.column_dimensions["E"].width = 20
    ws_cr.column_dimensions["F"].width = 8
    ws_cr.column_dimensions["G"].width = 25
    ws_cr.column_dimensions["H"].width = 12

    write_header(ws_cr, 1, cr_headers)
    for i, cr in enumerate(spec.censoring_rules, 2):
        write_row(ws_cr, i, [
            cr.rule_id, cr.rule_type, cr.rule_label, cr.description,
            cr.applies_to or "All", cr.page, cr.section or "",
            f"{cr.confidence:.0%}",
        ], confidence=cr.confidence)

    # ── Save ──────────────────────────────────────────────────────────
    path = Path(output_path)
    path.parent.mkdir(parents=True, exist_ok=True)
    wb.save(str(path))
    print(f"[Excel] Program spec saved: {path}")
    return str(path)
